config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        registrations: 'admins/registrations'
      }

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

   resources :boats  
   resources :jobs 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/boatjobs' => 'boatjobs#create'
  root to: "home#index"
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :boats, through: :boatjobs
	has_many :boatjobs
	
	validates :name, uniqueness: { :message => "That job name is already taken"}
	validates :description, :length => { minimum: 50, maximum: 1000, :message => ""}
	validates :cost, :numericality => { :greater_than => 1000.00, message:"" }
	validate :origin_location

	def origin_location
	 	locations_array = ["Tokyo", "Los Angles", "Hong Kong", "Sydney", "Portland", "New York"]
	 	if !locations_array.include? destination or !locations_array.include? origin
	 		errors.add(:location, "This is not a valid location") 
	 	end
	 end 
end

app/controllers/jobs/confirmations_controller.rb
class Jobs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/jobs/omniauth_callbacks_controller.rb
class Jobs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/jobs/passwords_controller.rb
class Jobs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/jobs/registrations_controller.rb
class Jobs::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/jobs/sessions_controller.rb
class Jobs::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/jobs/unlocks_controller.rb
class Jobs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @boats = Boat.all
    @jobs = Job.all
    @job = Job.new
  end

  def new
    @job = Job.new
    @boat_id = params[:boat_id] if params[:boat_id] #this says if there is a boat id to get the boat id
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      Boat.find(params[:boat_id]).jobs << @job if params[:boat_id] #this finds a boat by id and adds a job to the boat
      redirect_to jobs_path 
    else
      redirect_to jobs_path
    end
  end

  def update
  end

  def edit
  end

  def show

  end

  def destroy
    @job = Job.find(params[:id])#finds the job by its id
    respond_to do |format|
      if @job.destroy #this code sends you to the js page for destroy to delete the post with ajax
        format.js
      end
    end
  end

    private

  def job_params
    params.require(:job).permit(:description, :containers, :cost, :destination, :origin, :name)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_all_boats.html.erb
<% @boats.each do |boat| %>
	<div class="boat">
		<%= form_tag( '/boatjobs', :method => "post", remote: true) do %>
			<%= hidden_field_tag "job_id", "", class: "jobid" %>
			<%= hidden_field_tag "boat_id", boat.id %>
			Boat Name: <%= boat.name %>
			<br>
			Number of containers: <%= boat.containers%>
			<br>
			Location: <%= boat.location%>
			<br>
			<%= submit_tag ("Add Boat To Job"), :class => "addboat" %>
			<br>
		</div>
		<br>
	<% end %>
<% end %>

app/views/jobs/_find_job.html.erb
<div>
	<% @jobs.each do |job| %>
		<%= job.name %>
		<%= job.description %>
		<%= job.origin %>
		<%= job.destination %>
		<%= job.cost %>
		<%= job.containers %>
	<% end %>
</div>

app/views/jobs/_job.html.erb
<div class="job">
	Name: <%= job.name %>
	<br>
	Description: <%= job.description %>
	<br>
	Origin: <%= job.origin %>
	<br>
	Destination: <%= job.destination %>
	<br>
	Cost: <%= job.cost %>
	<br>
	Containers: <%= job.containers %>
	<br>
	<%= link_to "End Job", job_path(job), method: :delete, remote: true, class: 'destroy_job' %>
	<br>
	Boats on job:
	<% job.boats.each do |boat| %>
		<%= boat.name %>
	<% end %>
	<br>
	<%= hidden_field_tag "job_id", job.id, id: "jobidholder" %>
	<button class="fboat">Find A Boat</button>
	<br>
</div>

app/views/jobs/_new_job.html.erb
<%= form_for @job do |f| %>
	<% if @boat_id %>
		<%= hidden_field_tag :boat_id, @boat_id %>
	<% end %>
	<div class="control-group">
		<%= f.label :name, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :description, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :description %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :Origin, class: "control-label" %>
		<div class="controls">
			<%= f.select :origin, ["Tokyo", "Los Angles", "Hong Kong", "Sydney", "Portland", "New York"] %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :Destination, class: "control-label" %>
		<div class="controls">
			<%= f.select :destination, ["Tokyo", "Los Angles", "Hong Kong", "Sydney", "Portland", "New York"] %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :Cost, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :cost %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :Containers, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :containers %>
		</div>
	</div>
	<%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<p>Find me in app/views/jobs/index.html.erb</p>
<!-- Large modal --> 
<button type="button" id="mbut" class="btn btn-primary" data-target=".bs-example-modal-lg">New Job</button>

<div class="modal fade bs-example-modal-lg" id="jobmodal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
		<%= render "new_job" %>
    </div>
  </div>
</div>

<% if @job.errors.full_messages.any? %>   
    <ul>     
        <% @job.errors.full_messages.each do |error_message| %>       
        <li><%= error_message %></li> <br />     
        <% end %>   
    </ul> 
<% end %>

<div class="jobs">
	<% @jobs.each do |job| %>
		<%= render "job", job: job %>
	<% end %>
	<br>
</div>

<div class="modal fade bs-example-modal-lg" id="boatmodal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
		<%= render "all_boats" %>
    </div>
  </div>
</div>

app/views/jobs/index.js.erb
$('.addboat').on 'click'

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>

<%= render "new_job" %>

app/views/jobs/new.js.erb
$('.modal-content').html("<%= j render 'new_job' %>")

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>